language: php

php:
  - 7.0

env:
  - PHP_BIN="php-cgi"

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE facedown;'

script:
  - ./vendor/bin/tester -p $PHP_BIN -o console -s $coverage ./tests/

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
