language: php

php:
  - 7.0

env:
  - TESTER_PHP_BIN="php-cgi"

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE facedown;'
  #- mysql -u root facedown < tests/dump.sql
  #- mysql -u root facedown < tests/dataset.sql

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -o console -c ./tests/php.ini -s ./tests/
