language: php

php:
  - 7.0

env:
  - PHP_BIN="php-cgi"

matrix:
    include:
        - php: 7.0
          env: coverage="--coverage ./coverage.xml --coverage-src ./app" PHP_BIN=php-cgi

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE facedown;'

after_script:
  - >
    if [ "$coverage" != "" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php coveralls.phar --verbose --config tests/.coveralls.yml
    || true; fi

script:
  - ./vendor/bin/tester -p $PHP_BIN -d extension=xdebug.so -o console -s $coverage ./tests/

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
