language: php

php:
  - 7.0

env:
  - PHP_BIN="php-cgi"

matrix:
    include:
        - php: 7.0
          env: coverage="--coverage ./coverage.xml --coverage-src ./app" PHP_BIN=phpdbg

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE facedown;'

script:
  - ./vendor/bin/tester -p $PHP_BIN -o console -s ./tests/
